#ifndef __ANIMS_H__
#define __ANIMS_H__
// playerAnimations


typedef enum //# animNumber_e
{
	BOTH_DEATH_NORMAL,

	ANIM_START_DEATHS,

	BOTH_DEATH_NECK,
	BOTH_DEATH_CHEST_1,
	BOTH_DEATH_CHEST_2,
	BOTH_DEATH_GROIN_1,
	BOTH_DEATH_GROIN_2,
	BOTH_DEATH_GUT_1,
	BOTH_DEATH_GUT_2,
	BOTH_DEATH_HEAD_1,
	BOTH_DEATH_HEAD_2,
	BOTH_DEATH_SHOULDER_LEFT_1,
	BOTH_DEATH_SHOULDER_LEFT_2,
	BOTH_DEATH_ARMS_LEFT_1,
	BOTH_DEATH_ARMS_LEFT_2,
	BOTH_DEATH_LEGS_LEFT_1,
	BOTH_DEATH_LEGS_LEFT_2,
	BOTH_DEATH_LEGS_LEFT_3,
	BOTH_DEATH_THIGH_LEFT_1,
	BOTH_DEATH_THIGH_LEFT_2,
	BOTH_DEATH_ARMS_RIGHT_1,
	BOTH_DEATH_ARMS_RIGHT_2,
	BOTH_DEATH_LEGS_RIGHT_1,
	BOTH_DEATH_LEGS_RIGHT_2,
	BOTH_DEATH_LEGS_RIGHT_3,
	BOTH_DEATH_SHOULDER_RIGHT_1,
	BOTH_DEATH_SHOULDER_RIGHT_2,
	BOTH_DEATH_THIGH_RIGHT_1,
	BOTH_DEATH_THIGH_RIGHT_2,

	ANIM_END_DEATHS,

	TORSO_DROP,
	TORSO_DROP_ONEHANDED,
	TORSO_DROP_KNIFE,
	TORSO_RAISE,
	TORSO_RAISE_ONEHANDED,
	TORSO_RAISE_KNIFE,

	LEGS_IDLE,
	LEGS_IDLE_CROUCH,
	LEGS_WALK,
	LEGS_WALK_BACK,
	LEGS_WALK_CROUCH,
	LEGS_WALK_CROUCH_BACK,

	LEGS_RUN,
	LEGS_RUN_BACK,

	LEGS_SWIM,

	LEGS_JUMP,
	LEGS_JUMP_BACK,

	LEGS_TURN,

	LEGS_LEAN_LEFT,
	LEGS_LEAN_RIGHT,
	LEGS_LEAN_CROUCH_LEFT,
	LEGS_LEAN_CROUCH_RIGHT,

	LEGS_LEANLEFT_WALKLEFT,
	LEGS_LEANLEFT_WALKRIGHT,
	LEGS_LEANRIGHT_WALKLEFT,
	LEGS_LEANRIGHT_WALKRIGHT,

	LEGS_LEANLEFT_CROUCH_WALKLEFT,
	LEGS_LEANLEFT_CROUCH_WALKRIGHT,
	LEGS_LEANRIGHT_CROUCH_WALKLEFT,
	LEGS_LEANRIGHT_CROUCH_WALKRIGHT,

	TORSO_IDLE_KNIFE,
	TORSO_IDLE_PISTOL,
	TORSO_IDLE_RIFLE,
	TORSO_IDLE_MSG90A1,
	TORSO_IDLE_MSG90A1_ZOOMED,
	TORSO_IDLE_M4,
	TORSO_IDLE_M590,
	TORSO_IDLE_USAS12,
	TORSO_IDLE_RPG,
	TORSO_IDLE_M60,
	TORSO_IDLE_MM1,
	TORSO_IDLE_GRENADE,

	TORSO_ATTACK_KNIFE,
	TORSO_ATTACK_KNIFE_THROW,
	TORSO_ATTACK_PISTOL,
	TORSO_ATTACK_RIFLE,
	TORSO_ATTACK_MSG90A1_ZOOMED,
	TORSO_ATTACK_M4,
	TORSO_ATTACK_M590,
	TORSO_ATTACK_USAS12,
	TORSO_ATTACK_RIFLEBUTT,
	TORSO_ATTACK_RPG,
	TORSO_ATTACK_M60,
	TORSO_ATTACK_MM1,
	TORSO_ATTACK_GRENADE_START,
	TORSO_ATTACK_GRENADE_END,
	TORSO_ATTACK_BAYONET,
	TORSO_ATTACK_PISTOLWHIP,

	TORSO_RELOAD_M60,
	TORSO_RELOAD_PISTOL,
	TORSO_RELOAD_RIFLE,
	TORSO_RELOAD_MSG90A1,
	TORSO_RELOAD_RPG,
	TORSO_RELOAD_USAS12,

	TORSO_RELOAD_M590_START,
	TORSO_RELOAD_M590_SHELL,
	TORSO_RELOAD_M590_END,

	TORSO_RELOAD_MM1_START,
	TORSO_RELOAD_MM1_SHELL,
	TORSO_RELOAD_MM1_END,

	TORSO_USE,

	MAX_ANIMATIONS
} animNumber_t;

#endif// #ifndef __ANIMS_H__

